dist: trusty
branches:
  only:
    - master
    # tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  - npm

language: node_js
node_js:
  - 6
  - 8
  - 10

install:
  - npm install
  - if [[ $TRAVIS_NODE_VERSION == "6" ]]; then npm run prepare; fi

script:
  - npm run lint:js
  - npm run lint:types
  - npm test
  # `jest-puppeteer` doesn't work in Node 6
  - if [[ $TRAVIS_NODE_VERSION != "6" ]]; then npm run test:e2e; fi
  - node examples/build.js 100 100
