name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
      - name: Run E2E tests
        run: npm run test:e2e

      - name: Run example
        run: node examples/build.js 100 100

      - name: Collect coverage
        run: npm run coverage
        if: startsWith(matrix.node, '18')

      - name: Report coverage
        uses: codecov/codecov-action@v4
        if: startsWith(matrix.node, '18')
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true
